### ISSUE TITLE
Failed CSV generation 

### ISSUE THREAD

**Issue by sfougarisb** [IATI/IATI-Query-Builder#27]
After making a selection of the data I ma interested in and the URL is created, I get a page not found error 

url: http://datastore.iatistandard.org/api/1/access/budgets/by_country.csv?recipient-region=89&stream=True
![screen shot 2017-01-18 at 11 43 06](https://cloud.githubusercontent.com/assets/25195805/22056917/8eb0b824-dd73-11e6-9390-cb4106fad1cc.jpg)

Please assist if possible

**Comment by hayfield** [comment]
This URL is generated by selecting:

* *Choose Format* - One Budget per row
* *Repeat Rows?* - Multi-Country expansion
* *Choose Sample Size* - Entire selection
* *Select Region (eg South Asia = 679)* - 89: Europe, regional

A 404 error is also returned if selecting a Country rather than a region, or expanding by sector rather than country.

It works OK if opting for one transaction per row rather than one budget item per row.

**Comment by hayfield** [comment]
@dalepotter Any ideas as to why attempts to perform budget row expansion may lead to 404s?

**Comment by andylolz** [comment]
It looks as if there’s a typo in the generated URL: ‘budgets’ should be ‘budget’.

From the API docs (note budget always referred to in the singular):
>  * List of budgets [/api/1/access/budget.csv](http://datastore.iatistandard.org/api/1/access/budget.csv)
>  * Budgets by sector [/api/1/access/budget/by_sector.csv](http://datastore.iatistandard.org/api/1/access/budget/by_sector.csv)
>  * Budgets by country [/api/1/access/budget/by_country.csv](http://datastore.iatistandard.org/api/1/access/budget/by_country.csv)

Relevant line in the query builder (note the value of the radio is budgets):
https://github.com/IATI/IATI-Query-Builder/blob/a014d8c2/index.php#L246

**Comment by andylolz** [comment]
Looks like the change was made to the API in https://github.com/IATI/IATI-Datastore/commit/a794b8af

But the query builder was only partially updated to match in e87e986e
