### ISSUE TITLE
Missing .travis.yml

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Query-Builder#46]
Travis is enabled, but there’s no travis config file in the repo. So PRs are guaranteed to have a little red cross next to them.

E.g. https://travis-ci.org/IATI/IATI-Query-Builder/builds/257916291

**Comment by dalepotter** [comment]
Thanks for logging this @andylolz - there is no `.travis.yml` as no tests are written, and this repo was mistakenly turned o in our Travis set-up.

I've now disabled this repo from triggering Travis builds, so pull requests will not raise the 'All checks have failed' message.

Given that under current capacity this tool will still be around for at least the next six months, we should ideally set-up some tests - probably front-end selenium tests using PHPunit (since refactoring the code to make it testable would be a larger job).  I'll keep this open and I've added the initial set-up of this to our weekly maintenance and routine jobs, though this will be a lower priority given other maintenance tasks.
