### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Query-Builder#54]
Short-term work is ongoing to improve the query builder user interface.  This is part of a quick two day sprint we have been doing to make improvements to this tool. There is only one remaining day available for this work in this iteration, before the focus switches to improving the Datastore UI next week.

As of completed work right now, the development UI looks similar to the @andylolz version available here: http://please.treadsoft.ly/query/

Going forwards, the current thinking is to implement something like the below wireframe - immediate comments from users are very welcome, but we cannot guarantee will be implemented in this iteration. The next round of work on this tool will be to incorporate the new IATI brand, and further tweaks will be possible as part of ongoing weekly maintenance and small project work:

![img_20170920_104024472](https://user-images.githubusercontent.com/8247168/30637687-fe67c192-9df0-11e7-8b7b-2a6923695698.jpg)

![img_20170920_104033268](https://user-images.githubusercontent.com/8247168/30637688-fe689680-9df0-11e7-940a-99a718cf8aff.jpg)

**Comment by dalepotter** [comment]
Comment from @andylolz originally made in #49 (copying over to here so it is logged)...

> If you don’t mind a bit of javascript, you could have a radio / select to choose from two options:
 - [ ] country
 - [ ] region

> …and then this triggers which chosen select is displayed. That way it’s impossible for the user to do something weird, which is better UX (in the “don’t make me think” sort of sense.)

> More generally, though: These are all just filters, and most times I guess the user doesn’t care about the majority of these filters. So perhaps they should pick the ones they care about, and the rest should be hidden until needed.

> USAID explorer does exactly this – it’s lovely:
https://explorer.usaid.gov/query

A response from me:

> Nice idea too, I was also thinking about some pre-select 'country' vs. 'region' buttons, although was thinking these could be styled with a graphically too. But radio buttons is definitely more MVP!

**Comment by JamesCoe** [comment]
Hi @dalepotter -- really pleased that you're working on this! I think the query-builder is a really useful tool. My comments are below:

- For me, a key thing will be to change the names of the donors into more user-friendly formats. Some of them have strings of numbers next to them. Eventually you learn to ignore these parts, but it looks pretty daunting to new users. I know you're working on making selection easier as well, which is useful. 

- The "format", "repeated rows" and "sample size" are useful but should probably be rephrased a little so its clearer wheat they mean. On format, you could just put "activities", "transactions" or "budget" -- I'll have a think but there might be a better way of wording it so that its more accessible to non-IATI people. I've never understood what the "repeated rows" section means? On sample size, perhaps there's a way to 'opt-in' for a sample but the default is entire selection. 

- A way to select the entire sector would be useful. At the moment, I just hold ctrl and click -- this really isn't the end of the world though. 

- I'd consider removing the country codes and numbers relating to countries and regions, as these are just 'noise' to the user. 

- I don't understand what you mean by 'last changed'? 

- "Select who reports" is very IATI language. Could be something more like "Select donor, or other data publisher"? The vast majority will probably be after the donor data. 

Aside from that, there's a few functional things like the elements it downloads and the fact it (I think) removes sector codes when it downloads, but I appreciate that this sprint is around UI so we can discuss those another time.

Hope this helps!
