### ISSUE TITLE
The Reset button is weird when JS is disabled

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Query-Builder#87]
The `Reset` button doesn't clear the form when JS is disabled on the page. Instead it does nothing unless you have previously clicked `Build Query`, at which point it will allow you to reset to the state of the form when you last clicked `Build Query`.

**Comment by andylolz** [comment]
Works correctly for me. Which browser are you testing with?

**Comment by allthatilk** [comment]
Same browser.

**Comment by andylolz** [comment]
👻

**Comment by andylolz** [comment]
Aha – you mean it doesn’t clear the form post-submission? Apologies – yes, you’re absolutely right!

I guess the reset button could just be a link to the query builder or a submit button with `value="reset"`, and could be swapped for `type="reset"` in javascript…

Tbh I hadn’t realised `type="reset"` behaves this way (i.e. it resets to defaults, rather than blanking all form fields).
